projetoDaniel/Controllers/BusesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using projetoDaniel.Data;

using projetoDaniel.Models;
using System.Linq;



namespace projetoDaniel.Controllers
{
    [Authorize]
    public class BusesController : Controller
    {


        private readonly ProjectTestDataContext _ctx;

        public BusesController(ProjectTestDataContext ctx)
        {
            _ctx = ctx;
        }

        public IActionResult Index()
        {
            var model = _ctx.Buses.ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEdit(int? id)
        {

            Buses model = new Buses();
            if (id != null)
            {

                model = _ctx.Buses.Find(id);
            }

            return View(model);

        }
 
        [HttpPost]
        public IActionResult AddEdit(Buses model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {

                    _ctx.Buses.Add(model);

                }
                else
                {
                    _ctx.Buses.Update(model);

                }
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);

        }
        
        [HttpDelete]
        public IActionResult Excluir (int id)
        {
            var buses = _ctx.Buses.Find(id);

            if (buses == null)
            {
                return NotFound();
            }
            _ctx.Buses.Remove(buses);
            _ctx.SaveChanges();

            return NoContent();

        }
    }
}

projetoDaniel/Views/Buses/AddEdit.cshtml
@model Buses
@{
    ViewBag.Title = $"{(Model.Id == 0 ? "Adicionar" : "Editar")} Ônibus";



}

<h2>@ViewBag.Title</h2>
<form method="post">


    <div class="form-group">
        <label>Prefixo</label>
        <input type="text" asp-for="Prefixo" class="form-control" autofocus />
        <small class="is-invalid">
            <span asp-validation-for="Prefixo"></span>
        </small>
    </div>

    <div class="form-group">
        <label>Linha</label>
        <input type="number" asp-for="Linha" class="form-control" />
        <small class="is-invalid">
            <span asp-validation-for="Linha"></span>
        </small>
    </div>
    <div class="form-group">
        <label>Empresa</label>
        <input type="text" asp-for="Empresa" class="form-control" />
        <small class="is-invalid">
            <span asp-validation-for="Empresa"></span>
        </small>
    </div>
    <div class="form-group">
        <label>Quantidade de Lugares</label>
        <input type="number" asp-for="Quantidadelugares" class="form-control" />
        <small class="is-invalid">
            <span asp-validation-for="Quantidadelugares"></span>
        </small>
    </div>

    <button type="submit" class="btn btn-outline-dark">Enviar</button>
    <a asp-action="Index" asp-controller="Buses" class="btn btn-info">Cancelar</a>



</form>
@section scripts{ 

<script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>

}

projetoDaniel/Views/Buses/Index.cshtml
@model IEnumerable<Buses>


@{
    ViewBag.Title = "Listagem de Ônibus";
}


<h2>@ViewBag.Title</h2>




<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Id do Ônibus</th>
            <th>Prefixo do Ônibus</th>
            <th>Quantidade de Lugares</th>
            <th>Linha</th>
            <th>Empresa</th>
            <th></th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="bus-@item.Id">
                <td>@item.Id</td>
                <td>@item.Prefixo</td>
                <td>@item.Quantidadelugares</td>
                <td>@item.Linha</td>
                <td>@item.Empresa</td>
                <td>
                    <a class="btn btn-outline-success btn-sm" asp-action="AddEdit" asp-route-id="@item.Id">Editar</a>
                    <button onclick="excluir('@item.Id','@item.Prefixo')" class="btn btn-danger btn-sm">Excluir</button>

                </td>

            </tr>

        }
    </tbody>


</table>

<br />
<br />
<div>
    <p align="right">
        <a class="btn btn-success" asp-action="AddEdit" asp-controller="Buses">Adicionar Ônibus</a>
    </p>
</div>

<div data-id="0" class="modal" tabindex="-1" role="dialog" id="modal-del">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir o ônibus <strong><span id="prefixo-onibus"></span></strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-primary" onclick="delYes()">Sim</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>
    function excluir(id, prefixo) {

        $('#prefixo-onibus').text(prefixo);
        $('#modal-del').data('id',id).modal('show');
    }

    var _url = '@Url.Action("Excluir")';

    function delYes() {
        var _id = $('#modal-del').data('id');
        $.ajax({
            url: _url,
            data: { id : _id },
            dataType: 'json',
            type: 'delete',
            success: function () {
               //alert('Item Excluído!')
                toastr.success('Ônibus excluído com sucesso! :)', 'Avaliador de Intercamp');
                $('#bus-' + _id).remove();
            },
            error: function () {
                //  alert('Erro ao excluir!')
                toastr.error('Erro ao excluir ônibus  :(', 'Avaliador de Intercamp');
            },
            complete: function () {
                $('#modal-del').modal('hide');

            }

        });

    }
    </script>
}