projetoDaniel/Controllers/AvaliationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Exchange.WebServices.Data;
using System.Security.Claims;
using projetoDaniel.Data;
using projetoDaniel.Models;
using System.Linq;
using WebMatrix.WebData;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace projetoDaniel.Controllers
{
    [Authorize]
    public class AvaliationsController : Controller
    {
        private readonly ProjectTestDataContext _ctx;
        public AvaliationsController(ProjectTestDataContext ctx)
        {
            _ctx = ctx;
            
        }



        public IActionResult Index()
        {
            
            AvaliationsIndexVM viewModel = new AvaliationsIndexVM
            { 
                 Buses = _ctx.Buses.ToList(),
                Avaliation = _ctx.Avaliations.ToList(),
            };


            return View(viewModel);
        }

        [HttpGet]
        public IActionResult AddAvaliation()
        {

            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            AvaliationAddVM model = new AvaliationAddVM();
            model.UsuarioId = Convert.ToInt32(id);
            return View(model);

        }

        [HttpPost]
        public IActionResult AddAvaliation(Avaliation model)
        {
            if (ModelState.IsValid)
            {
                _ctx.Avaliations.Add(model);
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);




        }

    }
}

projetoDaniel/Controllers/BusesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using projetoDaniel.Data;

using projetoDaniel.Models;
using System.Linq;



namespace projetoDaniel.Controllers
{
    [Authorize]
    public class BusesController : Controller
    {


        private readonly ProjectTestDataContext _ctx;

        public BusesController(ProjectTestDataContext ctx)
        {
            _ctx = ctx;
        }

        public IActionResult Index()
        {
            var model = _ctx.Buses.ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddEdit(int? id)
        {

            Buses model = new Buses();
            if (id != null)
            {

                model = _ctx.Buses.Find(id);
            }

            return View(model);

        }
 
        [HttpPost]
        public IActionResult AddEdit(Buses model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {

                    _ctx.Buses.Add(model);

                }
                else
                {
                    _ctx.Buses.Update(model);

                }
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);

        }
        
        [HttpDelete]
        public IActionResult Excluir (int id)
        {
            var buses = _ctx.Buses.Find(id);

            if (buses == null)
            {
                return NotFound();
            }
            _ctx.Buses.Remove(buses);
            _ctx.SaveChanges();

            return NoContent();

        }
    }
}

projetoDaniel/Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using projetoDaniel.Data;
using projetoDaniel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using projetoDaniel.infra;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace projetoDaniel.Controllers
{
    public class ContaController:Controller
    {
        private readonly ProjectTestDataContext _ctx;

        public ContaController(ProjectTestDataContext ctx)
        {
            _ctx = ctx;
        }
        public IActionResult Login(string returnUrl) => View(new LoginVM { ReturnUrl = returnUrl });
            
        [HttpPost]
        public async Task<IActionResult> Login (LoginVM model)
        {

            var usuario = _ctx.Users.FirstOrDefault(u => u.Email.ToLower() == model.Email.ToLower()) ;
            if (usuario == null)
            {
                ModelState.AddModelError("Email", "Email não localizado");

            }
            else
            {
                if(usuario.Senha != model.Senha.Encrypt())
                {
                    ModelState.AddModelError("Senha", "Senha inválida");
                }

                if (ModelState.IsValid)
                {
                    var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                    identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()));
                    identity.AddClaim(new Claim(ClaimTypes.Email, usuario.Email));
                    identity.AddClaim(new Claim(ClaimTypes.Name, usuario.Nome));
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(
                     CookieAuthenticationDefaults.AuthenticationScheme,
                     principal,
                     new AuthenticationProperties()
                     {
                         IsPersistent = model.Lembrar
                     }
                        );

                    if (!string.IsNullOrEmpty(model.ReturnUrl) &&  Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);


                    }
                    return RedirectToAction("Index", "Buses");
                }

                
            }
            return View(model);

        }

        public async Task<IActionResult> logOut()
        {


            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                return RedirectToAction("Login");
        }
    }
}

projetoDaniel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Projeto Daniel | @ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/node_modules/toastr/build/toastr.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />

    <!-- Bootstrap core CSS -->


</head>
<body class="d-flex flex-column h-100">

    @Html.Partial("_menu")


    <div class="container">
        @RenderBody()
    </div>  



    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted">Test Project | @DateTime.Now.DayOfWeek</span>
        </div>
    </footer>

    <script src="~/node_modules/jquery/dist/jquery.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/node_modules/toastr/build/toastr.min.js"></script>
    @RenderSection("scripts", false)

</body>
</html>

projetoDaniel/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-action="Index" asp-controller="Home">Avaliador de Intercamp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Buses">Lista de Ônibus</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Avaliations">Lista de Avaliações</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="AddAvaliation" asp-controller="Avaliations">Avaliar</a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Olá @User.Identity.Name
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Conta" asp-action="LogOut">Logout</a>
                    </div>
                </li>

            }

            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-action="Login" asp-controller="Conta">Login</a>
                </li>
            }
        </ul>

    </div>
</nav>